services:
  db:
    image: postgres:17-alpine
    container_name: scripts-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5481:5432"

  backend:
    build:
      context: ./backend
    container_name: scripts-backend
    env_file:
      - ./.env.example
    environment:
      DATABASE_URL: ${DATABASE_URL}
      MONITOR_DOMAINS: ${MONITOR_DOMAINS}
      SCRIPTS_DIR: ${SCRIPTS_DIR}
    depends_on:
      - db
    ports:
      - "8888:8000"

  frontend:
    build:
      context: ./frontend
    container_name: scripts-frontend
    depends_on:
      - backend
    ports:
      - "3345:80"

volumes:
  db_data:
